Checking for travis command

diff --git a/travis-local/travis-local b/travis-local/travis-local
--- a/travis-local/travis-local
+++ b/travis-local/travis-local
@@ -5,6 +5,9 @@ if [ -n "$1" ]; then
   cd $1
 fi
 
+# Make sure we have the `travis` command installed
+command -v travis >/dev/null 2>&1 || { echo >&2 "`travis` command required but it's not installed. See https://github.com/phayes/deadci/tree/master/travis-local"; exit 1; }
+
 # Export constant environment variables
 export CI=true
 export TRAVIS=true
